'use client'

import { useState, useEffect } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { Brain, X, Flame, Clock, CheckCircle, XCircle, Sparkles, Award } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { cn } from '@/lib/utils'
import { useDashboardStore } from '@/lib/store'

interface Question {
  id: string
  question: string
  options: string[]
  correctIndex: number
  subject: string
}

// Mock questions generated by "Nexus AI" based on uploaded resources
const MOCK_QUESTIONS: Question[] = [
  {
    id: '1',
    question: 'What is the time complexity of binary search?',
    options: ['O(n)', 'O(log n)', 'O(n log n)', 'O(1)'],
    correctIndex: 1,
    subject: 'Data Structures'
  },
  {
    id: '2',
    question: 'Which data structure uses LIFO principle?',
    options: ['Queue', 'Stack', 'Array', 'Linked List'],
    correctIndex: 1,
    subject: 'Data Structures'
  },
  {
    id: '3',
    question: 'What does SQL stand for?',
    options: ['Structured Query Language', 'Simple Question Language', 'Standard Query Logic', 'System Query Language'],
    correctIndex: 0,
    subject: 'Database Management'
  },
  {
    id: '4',
    question: 'Which normal form eliminates transitive dependencies?',
    options: ['1NF', '2NF', '3NF', 'BCNF'],
    correctIndex: 2,
    subject: 'Database Management'
  },
  {
    id: '5',
    question: 'What is the purpose of the "this" keyword in JavaScript?',
    options: ['Declares a variable', 'References current object', 'Creates a function', 'Imports a module'],
    correctIndex: 1,
    subject: 'Web Development'
  },
]

export function PulseQuiz() {
  const { isPulseQuizActive, togglePulseQuiz, addFocusPoints } = useDashboardStore()
  const [currentQuestionIndex, setCurrentQuestionIndex] = useState(0)
  const [selectedAnswer, setSelectedAnswer] = useState<number | null>(null)
  const [isAnswered, setIsAnswered] = useState(false)
  const [score, setScore] = useState(0)
  const [isComplete, setIsComplete] = useState(false)
  const [questions] = useState(() => 
    [...MOCK_QUESTIONS].sort(() => Math.random() - 0.5).slice(0, 5)
  )
  const [timeRemaining, setTimeRemaining] = useState(30)

  const currentQuestion = questions[currentQuestionIndex]

  // Timer countdown
  useEffect(() => {
    if (!isPulseQuizActive || isAnswered || isComplete) return

    const timer = setInterval(() => {
      setTimeRemaining(prev => {
        if (prev <= 1) {
          // Auto-submit wrong answer on timeout
          setSelectedAnswer(-1)
          setIsAnswered(true)
          return 30
        }
        return prev - 1
      })
    }, 1000)

    return () => clearInterval(timer)
  }, [isPulseQuizActive, isAnswered, isComplete, currentQuestionIndex])

  const handleAnswer = (answerIndex: number) => {
    if (isAnswered) return
    
    setSelectedAnswer(answerIndex)
    setIsAnswered(true)

    if (answerIndex === currentQuestion.correctIndex) {
      setScore(prev => prev + 1)
    }
  }

  const handleNext = () => {
    if (currentQuestionIndex < questions.length - 1) {
      setCurrentQuestionIndex(prev => prev + 1)
      setSelectedAnswer(null)
      setIsAnswered(false)
      setTimeRemaining(30)
    } else {
      setIsComplete(true)
      // Award focus points based on score
      if (addFocusPoints) {
        addFocusPoints(score * 10)
      }
    }
  }

  const handleClose = () => {
    togglePulseQuiz()
    // Reset state for next time
    setTimeout(() => {
      setCurrentQuestionIndex(0)
      setSelectedAnswer(null)
      setIsAnswered(false)
      setScore(0)
      setIsComplete(false)
      setTimeRemaining(30)
    }, 300)
  }

  const handleSkipQuiz = () => {
    handleClose()
  }

  if (!isPulseQuizActive) return null

  return (
    <AnimatePresence>
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        className="fixed inset-0 z-50 bg-background/80 backdrop-blur-md flex items-center justify-center p-4"
      >
        <motion.div
          initial={{ scale: 0.9, y: 20 }}
          animate={{ scale: 1, y: 0 }}
          exit={{ scale: 0.9, y: 20 }}
          className="relative w-full max-w-lg"
        >
          {/* Glow effect */}
          <div className="absolute inset-0 rounded-3xl bg-gradient-to-br from-primary/20 via-accent/10 to-primary/20 blur-xl" />
          
          {/* Main card */}
          <div className="relative bg-card border-2 border-primary/30 rounded-3xl p-6 shadow-2xl overflow-hidden">
            {/* Decorative corner accents */}
            <div className="absolute top-0 left-0 w-20 h-20 border-t-2 border-l-2 border-primary/30 rounded-tl-3xl" />
            <div className="absolute bottom-0 right-0 w-20 h-20 border-b-2 border-r-2 border-accent/30 rounded-br-3xl" />

            {/* Header */}
            <div className="flex items-center justify-between mb-6">
              <div className="flex items-center gap-3">
                <motion.div
                  animate={{ rotate: [0, 360] }}
                  transition={{ duration: 3, repeat: Infinity, ease: 'linear' }}
                  className="w-10 h-10 rounded-xl bg-gradient-to-br from-primary/20 to-accent/20 flex items-center justify-center"
                >
                  <Brain className="w-5 h-5 text-primary" />
                </motion.div>
                <div>
                  <h2 className="text-lg font-bold text-foreground">5-Hour Pulse</h2>
                  <p className="text-xs text-muted-foreground">Powered by Nexus AI</p>
                </div>
              </div>
              <button
                onClick={handleClose}
                className="p-2 rounded-lg hover:bg-muted transition-colors text-muted-foreground hover:text-foreground"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            {/* Content */}
            {isComplete ? (
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                className="text-center py-8"
              >
                <motion.div
                  initial={{ scale: 0 }}
                  animate={{ scale: 1 }}
                  transition={{ type: 'spring', bounce: 0.5 }}
                  className="w-20 h-20 mx-auto rounded-full bg-gradient-to-br from-primary/20 to-accent/20 flex items-center justify-center mb-4"
                >
                  <Award className="w-10 h-10 text-primary" />
                </motion.div>
                <h3 className="text-2xl font-bold text-foreground mb-2">Quiz Complete!</h3>
                <p className="text-muted-foreground mb-4">
                  You scored <span className="text-primary font-bold">{score}</span> out of{' '}
                  <span className="font-bold">{questions.length}</span>
                </p>
                
                <div className="flex items-center justify-center gap-2 mb-6">
                  <Flame className="w-5 h-5 text-warning" />
                  <span className="text-sm font-medium text-warning">+{score * 10} Focus Points earned!</span>
                </div>

                <Button onClick={handleClose} className="w-full">
                  <Sparkles className="w-4 h-4 mr-2" />
                  Continue Studying
                </Button>
              </motion.div>
            ) : (
              <>
                {/* Progress bar */}
                <div className="flex items-center gap-3 mb-6">
                  <div className="flex-1 h-2 bg-muted rounded-full overflow-hidden">
                    <motion.div
                      initial={{ width: 0 }}
                      animate={{ width: `${((currentQuestionIndex + 1) / questions.length) * 100}%` }}
                      className="h-full bg-primary rounded-full"
                    />
                  </div>
                  <span className="text-sm text-muted-foreground">
                    {currentQuestionIndex + 1}/{questions.length}
                  </span>
                </div>

                {/* Timer */}
                <div className="flex items-center justify-between mb-4">
                  <span className="text-xs font-medium text-muted-foreground bg-muted/50 px-2 py-1 rounded">
                    {currentQuestion.subject}
                  </span>
                  <div className={cn(
                    "flex items-center gap-1.5 px-2 py-1 rounded-lg",
                    timeRemaining <= 10 ? "bg-destructive/20 text-destructive" : "bg-muted/50 text-muted-foreground"
                  )}>
                    <Clock className="w-3.5 h-3.5" />
                    <span className="text-sm font-mono font-medium">{timeRemaining}s</span>
                  </div>
                </div>

                {/* Question */}
                <motion.div
                  key={currentQuestion.id}
                  initial={{ opacity: 0, x: 20 }}
                  animate={{ opacity: 1, x: 0 }}
                  className="mb-6"
                >
                  <h3 className="text-lg font-semibold text-foreground mb-4">
                    {currentQuestion.question}
                  </h3>

                  <div className="space-y-2">
                    {currentQuestion.options.map((option, index) => {
                      const isSelected = selectedAnswer === index
                      const isCorrect = index === currentQuestion.correctIndex
                      const showResult = isAnswered

                      return (
                        <motion.button
                          key={index}
                          whileHover={!isAnswered ? { scale: 1.01 } : {}}
                          whileTap={!isAnswered ? { scale: 0.99 } : {}}
                          onClick={() => handleAnswer(index)}
                          disabled={isAnswered}
                          className={cn(
                            "w-full p-4 rounded-xl border-2 text-left transition-all flex items-center gap-3",
                            !isAnswered && "hover:border-primary/50 hover:bg-muted/50",
                            isSelected && !showResult && "border-primary bg-primary/10",
                            showResult && isCorrect && "border-primary bg-primary/20",
                            showResult && isSelected && !isCorrect && "border-destructive bg-destructive/10",
                            !showResult && !isSelected && "border-border bg-card"
                          )}
                        >
                          <span className={cn(
                            "w-8 h-8 rounded-lg flex items-center justify-center text-sm font-bold",
                            showResult && isCorrect && "bg-primary text-primary-foreground",
                            showResult && isSelected && !isCorrect && "bg-destructive text-destructive-foreground",
                            !showResult && "bg-muted text-muted-foreground"
                          )}>
                            {String.fromCharCode(65 + index)}
                          </span>
                          <span className="flex-1 text-sm font-medium">{option}</span>
                          {showResult && isCorrect && (
                            <CheckCircle className="w-5 h-5 text-primary" />
                          )}
                          {showResult && isSelected && !isCorrect && (
                            <XCircle className="w-5 h-5 text-destructive" />
                          )}
                        </motion.button>
                      )
                    })}
                  </div>
                </motion.div>

                {/* Actions */}
                <div className="flex gap-3">
                  <Button
                    variant="outline"
                    onClick={handleSkipQuiz}
                    className="flex-1"
                  >
                    Skip Quiz
                  </Button>
                  <Button
                    onClick={handleNext}
                    disabled={!isAnswered}
                    className="flex-1"
                  >
                    {currentQuestionIndex < questions.length - 1 ? 'Next Question' : 'See Results'}
                  </Button>
                </div>
              </>
            )}
          </div>
        </motion.div>
      </motion.div>
    </AnimatePresence>
  )
}
